const fs = require('fs');
const path = require('path');

// Variables de entorno con valores por defecto
const apiUrl = process.env.API_URL || '/api';
const wsUrl = process.env.WS_URL || apiUrl.replace('/api', '');
const production = process.env.NODE_ENV === 'production';

// Firebase config (same as development, can be overridden via env vars)
const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY || 'AIzaSyDYKyJU2Yz-BmrBLtZsp5GIXJ0a-ux61AI',
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || 'fitflow-84667.firebaseapp.com',
  projectId: process.env.FIREBASE_PROJECT_ID || 'fitflow-84667',
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || 'fitflow-84667.firebasestorage.app',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || '763474285236',
  appId: process.env.FIREBASE_APP_ID || '1:763474285236:web:60e2f6b65218cf0697bde1',
  measurementId: process.env.FIREBASE_MEASUREMENT_ID || 'G-Y46Y78NQJF',
  vapidKey:
    process.env.FIREBASE_VAPID_KEY ||
    'BDfO_-B-rwzcD7Jxg8vdqzCoGt197ocX5YyfxwAczugWuvVsHnSW6Ec8Cxl1liGp-zLByPlEJEVj9prVTR1FlDg',
};

const envContent = `// This file is auto-generated by scripts/set-env.js
// Do not edit manually

export const environment = {
  production: ${production},
  apiUrl: '${apiUrl}',
  wsUrl: '${wsUrl}',
  firebase: {
    apiKey: '${firebaseConfig.apiKey}',
    authDomain: '${firebaseConfig.authDomain}',
    projectId: '${firebaseConfig.projectId}',
    storageBucket: '${firebaseConfig.storageBucket}',
    messagingSenderId: '${firebaseConfig.messagingSenderId}',
    appId: '${firebaseConfig.appId}',
    measurementId: '${firebaseConfig.measurementId}',
    vapidKey: '${firebaseConfig.vapidKey}',
  },
};
`;

const targetPath = path.join(__dirname, '../src/environments/environment.prod.ts');

fs.writeFileSync(targetPath, envContent);
console.log(`✅ environment.prod.ts generated with:`);
console.log(`   - production: ${production}`);
console.log(`   - apiUrl: ${apiUrl}`);
console.log(`   - wsUrl: ${wsUrl}`);
console.log(`   - vapidKey: ${firebaseConfig.vapidKey ? '✓ SET' : '✗ EMPTY'}`);
