const fs = require('fs');
const path = require('path');

// Variables de entorno con valores por defecto
const apiUrl = process.env.API_URL || '/api';
const production = process.env.NODE_ENV === 'production';

const envContent = `// This file is auto-generated by scripts/set-env.js
// Do not edit manually

export const environment = {
  production: ${production},
  apiUrl: '${apiUrl}',
};
`;

const targetPath = path.join(__dirname, '../src/environments/environment.prod.ts');

fs.writeFileSync(targetPath, envContent);
console.log(`✅ environment.prod.ts generated with API_URL=${apiUrl}`);
