// This file is auto-generated by scripts/set-env.js
// Do not edit manually

export const environment = {
  production: false,
  apiUrl: 'https://fitflow-production-f7cf.up.railway.app/api',
  firebase: {
    apiKey: 'AIzaSyDYKyJU2Yz-BmrBLtZsp5GIXJ0a-ux61AI',
    authDomain: 'fitflow-84667.firebaseapp.com',
    projectId: 'fitflow-84667',
    storageBucket: 'fitflow-84667.firebasestorage.app',
    messagingSenderId: '763474285236',
    appId: '1:763474285236:web:60e2f6b65218cf0697bde1',
    measurementId: 'G-Y46Y78NQJF',
    vapidKey: '',
  },
};
